version: '2'
services:
  app: 
    container_name: app
    build: ./docker
    ports: 
      - "8080:80"
    volumes:
      - .:/var/www/
    depends_on:
      - solr
  solr:
    image: solr:7.5.0-slim
    ports:
      - "8983:8983"
    volumes:
      - ./solr:/opt/solr/server/solr/mycores
